-- TallerMap: catálogo central de servicios y tipos de establecimiento
-- Ejecutable varias veces sin duplicar datos.

create table if not exists public.tipos_establecimiento (
  id smallint generated by default as identity primary key,
  slug text not null unique,
  nombre text not null,
  descripcion text,
  activo boolean not null default true,
  orden smallint not null default 0
);

insert into public.tipos_establecimiento (slug,nombre,descripcion,orden) values
('taller-independiente','Taller independiente','Taller de reparación no vinculado oficialmente a una marca.',10),
('taller-multimarca','Taller multimarca','Taller que trabaja con distintas marcas de vehículos.',20),
('concesionario-oficial','Concesionario oficial','Concesionario autorizado por una marca, con venta y posventa.',30),
('servicio-oficial','Servicio oficial','Centro de reparación y mantenimiento autorizado por una marca.',40),
('especialista','Taller especialista','Especialista en una tecnología, sistema o tipo de vehículo.',50),
('neumaticos','Centro de neumáticos','Establecimiento especializado en neumáticos, dirección y suspensión.',60),
('carroceria','Centro de carrocería','Especialista en chapa, pintura, lunas o reparación de carrocería.',70)
on conflict (slug) do update set
  nombre=excluded.nombre,
  descripcion=excluded.descripcion,
  orden=excluded.orden,
  activo=true;

alter table public.talleres
  add column if not exists tipo_establecimiento_slug text,
  add column if not exists marca_oficial text,
  add column if not exists venta_vehiculos boolean not null default false,
  add column if not exists posventa_oficial boolean not null default false;

create index if not exists idx_talleres_tipo_establecimiento
  on public.talleres (tipo_establecimiento_slug);
create index if not exists idx_talleres_marca_oficial
  on public.talleres (marca_oficial);

create table if not exists public.servicios (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  nombre text not null,
  categoria text not null,
  sinonimos text[] not null default '{}',
  popular boolean not null default false,
  activo boolean not null default true,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.talleres_servicios (
  taller_id uuid not null references public.talleres(id) on delete cascade,
  servicio_id bigint not null references public.servicios(id) on delete cascade,
  confirmado boolean not null default true,
  created_at timestamptz not null default now(),
  primary key (taller_id, servicio_id)
);

create index if not exists idx_servicios_activo_categoria
  on public.servicios (activo,categoria,orden);
create index if not exists idx_talleres_servicios_servicio
  on public.talleres_servicios (servicio_id,taller_id);

insert into public.servicios (slug,nombre,categoria,sinonimos,popular,orden) values
('mecanica-general','Mecánica general','Mecánica y mantenimiento',array['mecanica','reparacion general','taller mecanico'],true,10),
('mantenimiento-programado','Revisión y mantenimiento programado','Mecánica y mantenimiento',array['revision','mantenimiento','revision oficial'],false,20),
('cambio-aceite-filtros','Cambio de aceite y filtros','Mecánica y mantenimiento',array['aceite','filtros','cambio de aceite'],true,30),
('pre-itv','Revisión Pre-ITV','Mecánica y mantenimiento',array['itv','preitv','revision itv'],true,40),
('frenos','Frenos','Mecánica y mantenimiento',array['pastillas','discos','frenado'],true,50),
('embrague','Embrague','Mecánica y mantenimiento',array['kit embrague','volante bimasa'],false,60),
('correa-distribucion','Correa de distribución','Mecánica y mantenimiento',array['distribucion','correa motor'],false,70),
('cadena-distribucion','Cadena de distribución','Mecánica y mantenimiento',array['cadena motor','distribucion'],false,80),
('reparacion-motor','Reparación de motor','Mecánica y mantenimiento',array['motor','culata','averia motor'],false,90),
('sistema-refrigeracion','Sistema de refrigeración','Mecánica y mantenimiento',array['radiador','refrigerante','sobrecalentamiento'],false,100),
('escape-catalizador','Escape y catalizador','Mecánica y mantenimiento',array['escape','catalizador','filtro particulas'],false,110),
('caja-cambios','Caja de cambios','Mecánica y mantenimiento',array['cambio automatico','transmision','cambio manual'],false,120),
('neumaticos','Neumáticos','Neumáticos, dirección y suspensión',array['ruedas','cubiertas','pinchazo'],true,130),
('alineacion-direccion','Alineación y dirección','Neumáticos, dirección y suspensión',array['paralelo','alineado','geometria'],false,140),
('equilibrado-ruedas','Equilibrado de ruedas','Neumáticos, dirección y suspensión',array['equilibrado','vibracion ruedas'],false,150),
('suspension-amortiguadores','Suspensión y amortiguadores','Neumáticos, dirección y suspensión',array['amortiguadores','suspension'],false,160),
('direccion','Sistema de dirección','Neumáticos, dirección y suspensión',array['direccion asistida','cremallera'],false,170),
('diagnosis-electronica','Diagnosis electrónica','Electricidad y diagnosis',array['diagnosis','maquina diagnosis','ordenador'],true,180),
('electricidad-automovil','Electricidad del automóvil','Electricidad y diagnosis',array['electricidad','electricista coche'],false,190),
('baterias','Baterías','Electricidad y diagnosis',array['bateria','arranque bateria'],true,200),
('alternador-motor-arranque','Alternador y motor de arranque','Electricidad y diagnosis',array['alternador','motor arranque','arranque'],false,210),
('centralitas-electronica','Centralitas y electrónica','Electricidad y diagnosis',array['centralita','ecu','electronica'],false,220),
('sistemas-adas','Sistemas ADAS y ayudas a la conducción','Electricidad y diagnosis',array['adas','calibracion camara','radar'],false,230),
('llaves-codificacion','Llaves y codificación','Electricidad y diagnosis',array['llaves coche','codificar llave','inmovilizador'],false,240),
('chapa-pintura','Chapa y pintura','Carrocería y cristales',array['pintura','chapa','golpe carroceria'],true,250),
('carroceria','Reparación de carrocería','Carrocería y cristales',array['carroceria','golpes','siniestro'],false,260),
('lunas-cristales','Lunas y cristales','Carrocería y cristales',array['luna','parabrisas','cristal'],false,270),
('desabollado-sin-pintura','Desabollado sin pintura','Carrocería y cristales',array['varillero','abolladura','granizo'],false,280),
('tapiceria','Tapicería','Carrocería y cristales',array['asientos','techo coche','tapizado'],false,290),
('aire-acondicionado','Aire acondicionado','Climatización',array['aire','clima','carga gas'],true,300),
('calefaccion-climatizacion','Calefacción y climatización','Climatización',array['calefaccion','climatizador'],false,310),
('hibridos-electricos','Vehículos híbridos y eléctricos','Híbridos y eléctricos',array['electrico','hibrido','coche electrico'],true,320),
('baterias-alta-tension','Baterías de alta tensión','Híbridos y eléctricos',array['bateria hibrida','bateria electrica','alta tension'],false,330),
('cargadores-vehiculo-electrico','Cargadores para vehículo eléctrico','Híbridos y eléctricos',array['wallbox','cargador electrico','punto carga'],false,340),
('furgonetas','Furgonetas','Vehículos especiales',array['furgoneta','vehiculo comercial'],false,350),
('vehiculos-industriales','Vehículos industriales','Vehículos especiales',array['camion','industrial','vehiculo pesado'],false,360),
('autocaravanas','Autocaravanas','Vehículos especiales',array['autocaravana','camper'],false,370),
('vehiculos-4x4','Vehículos 4x4','Vehículos especiales',array['4x4','todoterreno'],false,380),
('equipos-sonido','Equipos de sonido y audio para automóvil','Personalización y multimedia',array['audio','altavoces','sonido coche'],false,390),
('multimedia-navegacion','Pantallas, multimedia y navegación','Personalización y multimedia',array['pantalla','navegador','carplay'],false,400),
('vinilos-rotulacion','Vinilos y rotulación','Personalización y multimedia',array['vinilo','rotulacion'],false,410),
('wrapping','Wrapping integral y cambio de color','Personalización y multimedia',array['wrapping','cambio color','vinilo integral'],false,420),
('tuning-personalizacion','Tuning y personalización','Personalización y multimedia',array['tuning','personalizacion'],false,430),
('iluminacion-automovil','Iluminación y sistemas LED','Personalización y multimedia',array['luces','led','faros'],false,440),
('grua-asistencia','Grúa y asistencia en carretera','Otros servicios',array['grua','asistencia','averia carretera'],false,450),
('lavado-detailing','Lavado y detailing','Otros servicios',array['lavado','detailing','limpieza coche'],false,460),
('montaje-accesorios','Montaje de accesorios','Otros servicios',array['accesorios','montaje'],false,470),
('homologaciones','Homologaciones','Otros servicios',array['homologar','reforma vehiculo'],false,480),
('instalacion-glp','Instalación y mantenimiento GLP','Otros servicios',array['glp','autogas','gas coche'],false,490),
('venta-vehiculos-nuevos','Venta de vehículos nuevos','Concesionario y compraventa',array['coche nuevo','vehiculo nuevo','venta concesionario'],false,500),
('venta-vehiculos-ocasion','Venta de vehículos de ocasión','Concesionario y compraventa',array['segunda mano','ocasion','seminuevo','coche usado'],false,510),
('recambios-originales','Recambios originales','Concesionario y compraventa',array['repuestos originales','piezas originales','recambios marca'],false,520),
('garantia-oficial','Garantía oficial y campañas de marca','Concesionario y compraventa',array['garantia','campaña marca','revision garantia'],false,530),
('vehiculo-sustitucion','Vehículo de sustitución','Concesionario y compraventa',array['coche sustitucion','vehiculo cortesia'],false,540),
('tasacion-vehiculos','Tasación de vehículos','Concesionario y compraventa',array['tasacion','valorar coche','comprar coche'],false,550)
on conflict (slug) do update set
  nombre=excluded.nombre,
  categoria=excluded.categoria,
  sinonimos=excluded.sinonimos,
  popular=excluded.popular,
  activo=true,
  orden=excluded.orden,
  updated_at=now();

alter table public.servicios enable row level security;
alter table public.tipos_establecimiento enable row level security;
alter table public.talleres_servicios enable row level security;

drop policy if exists "Servicios públicos activos" on public.servicios;
create policy "Servicios públicos activos" on public.servicios
for select to anon,authenticated using (activo=true);

drop policy if exists "Tipos públicos activos" on public.tipos_establecimiento;
create policy "Tipos públicos activos" on public.tipos_establecimiento
for select to anon,authenticated using (activo=true);

drop policy if exists "Relaciones públicas de servicios" on public.talleres_servicios;
create policy "Relaciones públicas de servicios" on public.talleres_servicios
for select to anon,authenticated using (true);
